### ISSUE TITLE
program fails, when searching in tunein

### ISSUE THREAD

**Issue by martinkg** [anonbeat/guayadeque#4] opened 2016-05-20 09:22 UTC
i use recent git version

`11:15:58: Should do the search now: 'deluro'
11:15:58: SetSearchText
[New Thread 0x7fffda552700 (LWP 45058)]
[Thread 0x7fffda552700 (LWP 45058) exited]
[New Thread 0x7fffda552700 (LWP 45059)]
[Thread 0x7fffda552700 (LWP 45059) exited]
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
guayadeque: xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

Thread 1 "guayadeque" received signal SIGABRT, Aborted.
0x00007ffff351ee55 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0  0x00007ffff351ee55 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff3520a5a in __GI_abort () at abort.c:89
#2  0x00007ffff35176f7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7ffff1b0e790 "!xcb_xlib_threads_sequence_lost", file=file@entry=0x7ffff1b0e5eb "xcb_io.c", line=line@entry=274, function=function@entry=0x7ffff1b0ea98 <__PRETTY_FUNCTION__.14485> "poll_for_event") at assert.c:92
#3  0x00007ffff35177a2 in __GI___assert_fail (assertion=assertion@entry=0x7ffff1b0e790 "!xcb_xlib_threads_sequence_lost", file=file@entry=0x7ffff1b0e5eb "xcb_io.c", line=line@entry=274, function=function@entry=0x7ffff1b0ea98 <__PRETTY_FUNCTION__.14485> "poll_for_event")
    at assert.c:101
#4  0x00007ffff1a9ba99 in poll_for_event (dpy=dpy@entry=0x555555e60400) at xcb_io.c:271
#5  0x00007ffff1a9bb4b in poll_for_response (dpy=dpy@entry=0x555555e60400) at xcb_io.c:289
#6  0x00007ffff1a9be6d in _XEventsQueued (dpy=dpy@entry=0x555555e60400, mode=mode@entry=2) at xcb_io.c:363
#7  0x00007ffff1a8d74f in XPending (dpy=0x555555e60400) at Pending.c:55
#8  0x00007ffff2577151 in gdk_event_source_check (display=<optimized out>) at gdkeventsource.c:269
#9  0x00007ffff2577151 in gdk_event_source_check (source=0x555555e82350) at gdkeventsource.c:306
#10 0x00007ffff589f471 in g_main_context_check (context=context@entry=0x555555e82440, max_priority=2147483647, fds=fds@entry=0x5555560d7650, n_fds=n_fds@entry=3) at gmain.c:3681
#11 0x00007ffff589f9e4 in g_main_context_iterate (context=0x555555e82440, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3837
#12 0x00007ffff589fdd2 in g_main_loop_run (loop=0x5555561fd280) at gmain.c:4034
#13 0x00007ffff2a0ed95 in gtk_main () at gtkmain.c:1269
#14 0x00007ffff734d185 in wxGUIEventLoop::DoRun() (this=0x555556164450) at src/gtk/evtloop.cpp:65
#15 0x00007ffff79eed7e in wxEventLoopBase::Run() (this=0x555556164450) at src/common/evtloopcmn.cpp:78
#16 0x00007ffff79b4669 in wxAppConsoleBase::MainLoop() (this=0x555555e39ad0) at src/common/appbase.cpp:334
#17 0x00007ffff7a3f93e in wxEntry(int&, wchar_t**) (argc=<optimized out>, argv=<optimized out>) at src/common/init.cpp:495
#18 0x000055555569fdd8 in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/guayadeque-c987cc99d9212d7283b6f5a8fc984c46135e22b7/src/MainApp.cpp:39`

**Comment by anonbeat** [comment] 2016-05-20 23:09
I cant reproduce it here. Please can you provide more information about thow to fire the bug?

Thanks for your help

**Comment by martinkg** [comment] 2016-05-25 08:46
at the moment not reproducable, will close ticket.

**Comment by anonbeat** [comment] 2016-06-04 06:40
Looks like it is random... I continue working on it.

**Comment by anonbeat** [comment] 2016-06-04 09:36
Fixed now!!

**Closed by anonbeat** 2016-06-04 09:36 UTC
