### ISSUE TITLE
Crash when using DBus to play

### ISSUE THREAD

**Issue by wojnilowicz** [anonbeat/guayadeque#96] opened 2020-05-17 06:23 UTC
Steps to reproduce:
1) start guayadeque
2) add a directory with an album to play (it has front.jpg as its cover)
3) make sure View->Cover is checked
4) press play
5) minimize to system tray
6) open terminal
7) invoke
"qdbus org.mpris.guayadeque /Player org.freedesktop.MediaPlayer.Play"
couple of times

Result (as terminal output):
Changed image to 1 '/my_image_path/front.jpg'
../src/common/image.cpp(432): assert "(width > 0) && (height > 0)" failed in Scale(): invalid new image size

Expected result:
No crash.

Additional information:
1) crash doesn't happen if guayadeque window is opened and not minimized to the system tray

**Comment by anonbeat** [comment] 2020-05-17 13:02
Cant reproduce it here.. Can you send me the crash report by email ?

**Comment by wojnilowicz** [comment] 2020-05-17 13:07
Have you tried several times? It usually doesn't happen at first use of dbus. It often happens at second use but can also happen at fifth.

It's also important that it's in the system tray.

**Comment by anonbeat** [comment] 2020-05-18 06:04
Yes tried several times with guayadeque closed to tray icon

**Comment by wojnilowicz** [comment] 2020-05-18 06:57
Recently Fedora provided update to guayadeque 0.4.6-b08bddd and new bug appeared, because after
"qdbus org.mpris.guayadeque /Player org.freedesktop.MediaPlayer.Play"
playlist gets cleared. This app is way too buggy for me. Here are the errors that I get
[guayadeque.log](https://github.com/anonbeat/guayadeque/files/4642486/guayadeque.log)
[guayadeque2.log](https://github.com/anonbeat/guayadeque/files/4642492/guayadeque2.log)
[guayadeque3.log](https://github.com/anonbeat/guayadeque/files/4642501/guayadeque3.log)
![guayadeque error](https://user-images.githubusercontent.com/22069602/82183061-96040500-98e5-11ea-9be4-74c427a617f9.png)
![guayadeque error2](https://user-images.githubusercontent.com/22069602/82183070-98665f00-98e5-11ea-91f1-935493ac3097.png)
![guayadeque error3](https://user-images.githubusercontent.com/22069602/82183073-9ac8b900-98e5-11ea-82ad-4eb5519f6831.png)

**Comment by wojnilowicz** [comment] 2020-05-18 07:04
and here is a dump from coredumpctl
[guayadeqedump.log](https://github.com/anonbeat/guayadeque/files/4642531/guayadeqedump.log)

**Comment by anonbeat** [comment] 2020-05-18 12:47
Thanks for the bug report. It have been fixed with dffe91c825943ab308beb26ed45315108fcd6c78

**Closed** 2020-05-18 13:00 UTC
Labels: bug

**Comment by wojnilowicz** [comment] 2020-05-18 15:13
> Thanks for the bug report. It have been fixed with [dffe91c](https://github.com/anonbeat/guayadeque/commit/dffe91c825943ab308beb26ed45315108fcd6c78)

That's great. Thanks. Did you also tackle that playlist gets cleared?

**Comment by anonbeat** [comment] 2020-05-18 18:33
Yes that was fixed also when mpris method was used.
